apiVersion: v1
kind: Pod
metadata:
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'devweb-app'
    vault.hashicorp.com/agent-inject-secret-atlas: 'database/creds/my-role'
    vault.hashicorp.com/agent-inject-template-atlas: |
      {{ with secret "database/creds/my-role" -}}
        export MONGODB_URI="mongodb+srv://{{ .Data.username }}:{{ .Data.password }}@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority"
      {{- end }}    
    vault.hashicorp.com/agent-inject-secret-atlasapi: 'kv/atlas/api-readonly'
    vault.hashicorp.com/agent-inject-template-atlasapi: |
      {{ with secret "kv/atlas/api-readonly" -}}
          export MONGODB_ATLAS_PUBLIC_API_KEY="{{ .Data.data.MONGODB_ATLAS_PUBLIC_API_KEY }}"
          export MONGODB_ATLAS_PRIVATE_API_KEY="{{ .Data.data.MONGODB_ATLAS_PRIVATE_API_KEY }}"
          export MONGODB_ATLAS_PROJECT_ID="{{ .Data.data.MONGODB_ATLAS_PROJECT_ID }}"
          export MONGODB_ATLAS_CLUSTER_NAME="{{ .Data.data.MONGODB_ATLAS_CLUSTER_NAME }}"
      {{- end }}
    vault.hashicorp.com/agent-init-first: 'true'
    vault.hashicorp.com/agent-cache-enable: "true"
  labels:
    app: devwebapp
  name: devwebapp
  namespace: mongodb
spec:
  serviceAccountName: internal-app
  initContainers:
    - image: centos
      name: wait-db-user-ready
      command: 
      - "sh"
      - "-c"
      args:
      - >
        source /vault/secrets/atlasapi; 
        source /vault/secrets/atlas;
        echo $MONGODB_ATLAS_PUBLIC_API_KEY;
        while [ -z $(grep "APPLIED" /tmp/atlas.json) ]; do 
          cat /tmp/atlas.json;
          curl -# --user "$MONGODB_ATLAS_PUBLIC_API_KEY:$MONGODB_ATLAS_PRIVATE_API_KEY" --digest --header "Content-Type: application/json" --include -o /tmp/atlas.json --request GET "https://cloud.mongodb.com/api/atlas/v1.0/groups/$MONGODB_ATLAS_PROJECT_ID/clusters/$MONGODB_ATLAS_CLUSTER_NAME/status?pretty=true";
          sleep 5;
        done;
        cat /tmp/atlas.json;
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: app
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']